source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'
gem 'faraday'
gem 'faraday-net_http_persistent'
gem 'yaml'
gem 'json'
gem 'rake'
gem 'dotenv'
gem 'sinatra'
gem 'puma'
gem 'faraday-retry'
gem 'httplog'
gem 'sinatra-reloader', groups: [:development]
gem 'bcrypt'
gem 'kramdown'
